import {
  colors,
  spacing,
  borderRadius,
  typography,
  breakpoints,
  icon,
} from '@/core/constants/theme';

export const lightTheme = {
  colors: {
    background: '#ffffff',
    surface: '#f8fafc',
    surfaceVariant: '#f1f5f9',
    overlay: 'rgba(15, 23, 42, 0.45)',
    text: '#0f172a',
    textSecondary: '#475569',
    textDisabled: '#94a3b8',
    inputPlaceholder: '#94a3b8',
    border: '#e2e8f0',
    divider: '#f1f5f9',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
    onError: '#ffffff',
    successSoft: 'rgba(16, 185, 129, 0.16)',
    successSoftBorder: 'rgba(16, 185, 129, 0.36)',
    warningSoft: 'rgba(245, 158, 11, 0.16)',
    warningSoftBorder: 'rgba(245, 158, 11, 0.36)',
    errorSoft: 'rgba(239, 68, 68, 0.16)',
    errorSoftBorder: 'rgba(239, 68, 68, 0.36)',
    primary: colors.primary,
    primaryLight: colors.primaryLight,
    primaryDark: colors.primaryDark,
    secondary: colors.secondary,
    secondaryLight: colors.secondaryLight,
    secondaryDark: colors.secondaryDark,
    success: colors.success,
    successLight: colors.successLight,
    successDark: colors.successDark,
    warning: colors.warning,
    warningLight: colors.warningLight,
    warningDark: colors.warningDark,
    error: colors.error,
    errorLight: colors.errorLight,
    errorDark: colors.errorDark,
    info: colors.info,
    infoLight: colors.infoLight,
    infoDark: colors.infoDark,
  },
  spacing,
  borderRadius,
  typography,
  breakpoints,
  shadows: {
    xs: {
      elevation: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 1,
    },
    sm: {
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
    },
    md: {
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 4,
    },
    lg: {
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
    },
    xl: {
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 8,
    },
  },
  icon,
  name: 'light',
};

export const darkTheme = {
  colors: {
    background: '#0f172a',
    surface: '#1e293b',
    surfaceVariant: '#334155',
    overlay: 'rgba(15, 23, 42, 0.7)',
    text: '#f8fafc',
    textSecondary: '#cbd5e1',
    textDisabled: '#64748b',
    inputPlaceholder: '#94a3b8',
    border: '#334155',
    divider: '#1e293b',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
    onError: '#ffffff',
    successSoft: 'rgba(16, 185, 129, 0.16)',
    successSoftBorder: 'rgba(16, 185, 129, 0.36)',
    warningSoft: 'rgba(245, 158, 11, 0.16)',
    warningSoftBorder: 'rgba(245, 158, 11, 0.36)',
    errorSoft: 'rgba(239, 68, 68, 0.16)',
    errorSoftBorder: 'rgba(239, 68, 68, 0.36)',
    primary: colors.primary,
    primaryLight: colors.primaryLight,
    primaryDark: colors.primaryDark,
    secondary: colors.secondary,
    secondaryLight: colors.secondaryLight,
    secondaryDark: colors.secondaryDark,
    success: colors.success,
    successLight: colors.successLight,
    successDark: colors.successDark,
    warning: colors.warning,
    warningLight: colors.warningLight,
    warningDark: colors.warningDark,
    error: colors.error,
    errorLight: colors.errorLight,
    errorDark: colors.errorDark,
    info: colors.info,
    infoLight: colors.infoLight,
    infoDark: colors.infoDark,
  },
  spacing,
  borderRadius,
  typography,
  breakpoints,
  shadows: {
    xs: {
      elevation: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 1,
    },
    sm: {
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
    },
    md: {
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
    },
    lg: {
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    xl: {
      elevation: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
    },
  },
  icon,
  name: 'dark',
};

export type Theme = typeof lightTheme;
